application: solid-choir-601
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: menu.application


error_handlers:
  - file: default_error.html

  - error_code: over_quota
    file: over_quota.html